language: php

php:
  - 5.4
  - 5.5
  - 5.6

services: redis-server

before_script:
  - composer self-update
  - composer install --prefer-source

script: ./vendor/bin/phpunit -c phpunit.xml.travis.dist